version: '3.7'

services:

  frontend:
    container_name: frontend
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start